[[constraint]]
  name="github.com/spf13/cobra"
  version = "v0.0.5"

[[constraint]]
  name="github.com/metakeule/fmtdate"
  version = "v1.1.2"

[[constraint]]
  name="github.com/brettski/go-termtables"
  version = "v1.0"
  
[[override]]
  name = "github.com/russross/blackfriday"
  version = "1.5.2"