name: Go
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Get dependencies
      run: |
        pwd
        if [ -f Gopkg.toml ]; then
            mkdir -p /home/runner/go/{bin,src}
            GOBIN="/home/runner/go/bin"
            GOPATH="/home/runner/go/"
            mv /home/runner/work/elasticman/elasticman /home/runner/go/src/elasticman && cd /home/runner/go/src/elasticman
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            $GOBIN/dep ensure
        fi

    - name: Build
      run: go build -v .
